### ISSUE TITLE
HW Flow Control Needed for TH-D72

### ISSUE THREAD

**Issue by mobilinkd** [maqifrnswa/PCSI#8]
I am unable to receive packets with a TH-D72 because it appears to require HW flow control in KISS TNC mode via USB serial.  I tried setting FLOW OFF and XFLOW ON before entering KISS mode but that did not help.  Software flow control cannot work in KISS mode.

Transmit seems to work fine, but I suspect that it expects the CTS signal to be honored.

**Comment by maqifrnswa** [comment]
acked - I have a TH-D72 too, so I can check it out. That should be an easy fix

**Comment by maqifrnswa** [comment]
I turned on hardware handshaking and received some packets OK on a TH-D72. I think the problem actual was some extra incomplete packets left in the serial port, so I cleared it out.  But I turned on the handshaking just in case.
https://github.com/maqifrnswa/PCSI/commit/a16cb470319fbda6f23d1ccd3d9231b8aacc9312

I can transmit images from a TH-D72a and receive on a hamshield perfectly fine. I can't get the other direction to work, but I can't tell if the problem is with the hamshield or TH-D72a. The packets are ended prematurely (FEND flags show up where there shouldn't be any).

I'll keep this bug open for now until we confirm it's fixed. If you could test and confirm the git head works, I'd appreciate it.

**Comment by mobilinkd** [comment]
Works for me.
